version: '3.5'
services:
    web:
        container_name: app-api
        image: mtakashimori/laravel
        command: php artisan serve --host=0.0.0.0 --port=80
        working_dir: .:/var/www/html/app
        entrypoint: ['/bin/sh', '/var/www/html/app/entrypoint.sh']
        volumes:
            - .:/var/www/html/app
        tty: true
        networks:
            main:
                aliases:
                    - web
    db:
        container_name: app-db
        image: mariadb:10.4
        networks:
            main:
                aliases:
                    - db
networks:
    main:
