version: '3.5'
services:
  web:    
    ports:
        - "8000:80"
  db:
    ports:
        - "3306:3306"
    volumes:
        - /var/www/html/app:/var/lib/mysql
    environment:
        MYSQL_USER_PASSWORD: p@ssw0rd_root
        MYSQL_DATABASE: app-database
        MYSQL_USER: user
        MYSQL_PASSWORD: p@ssw0rd
